Slave
prplmad/Monitoring pull request #1
Opened 2022-10-21 18:50 UTC by prplmad

2022-10-22 11:48 UTC, alexander-eltsov requested changes
Замечания не критичные, но лучше поправить сразу

2022-10-22 11:48 UTC, alexander-eltsov commented on BL/BL.csproj
> +      <Compile Remove="Class1.cs" />
Лишнее осталось от созданного проекта по шаблону

2022-10-22 11:48 UTC, alexander-eltsov commented on BL/Abstract/Services/IStatisticsControllerService.cs
> +public interface IStatisticsControllerService
Не самое удачное название IStatistics**Controller**Service. Наводит на мысль, что ответственость этого сервиса заключается в оказании помощи работы контроллера но так быть не должно. Направление зависимостей  строго вовнутрь, контроллеры зависят от абстракций сервисов, а не наоборот. Технически оно так и есть сейчас, но порой подобный нейминг может сбить с толку коллегу-разработчика и возникнет желание напихать в этот сервис хелпер-методов для нужд контроллера, которые совершенно не вписываются в логику предметной области.

2022-10-22 11:48 UTC, alexander-eltsov commented on DAL/DAL.csproj
> +      <Compile Remove="Class1.cs" />
Тоже лишнее

2022-10-24 08:08 UTC, SergerGood requested changes

2022-10-24 08:08 UTC, SergerGood commented on Monitoring.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "BL", "BL\BL.csproj", "{FB6D2C3E-C799-4081-8131-1185B7A76FFA}"
Названия проектов не очевидные и содержать сокращения в именовании. DAL я еще встречал, но вот BL - нет. Вроде по предложенной ссылке есть примеры https://code-maze.com/onion-architecture-in-aspnetcore/#Solution%20Structure

2022-10-24 08:08 UTC, SergerGood commented on BL/Services/StatisticsControllerService.cs
> +public class StatisticsControllerService
Написание комментариев у нас обязательная практика и проверяется линтерами. Поэтмоу рекомендую сразу подключить и стараться писать.
Для CodeCleanup - https://msk-tfs-t.infotecs-nt/tfs/SrvNccCollection/NSMS/_git/settings_files?path=%2F.editorconfig

Для проверок -https://msk-tfs-t.infotecs-nt/tfs/SrvNccCollection/NSMS/_git/settings_files?path=%2Finfotecs.ruleset

https://wiki.infotecs.int/pages/viewpage.action?pageId=69214455

2022-10-24 08:09 UTC, SergerGood commented on BL/Services/StatisticsControllerService.cs
> +public class StatisticsControllerService
ссылки внутренние

2022-10-24 08:45 UTC, prplmad commented on BL/Services/StatisticsControllerService.cs
> +public class StatisticsControllerService
К первым двум ссылкам кажется у меня нет доступа. Ошибка TF400734: эта служба доступна только на размещенном Azure DevOps. (офисный пк)

2022-10-24 08:48 UTC, prplmad commented on Monitoring.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "BL", "BL\BL.csproj", "{FB6D2C3E-C799-4081-8131-1185B7A76FFA}"
Ознакомился и уже переписываю

2022-10-24 08:54 UTC, prplmad commented on BL/Abstract/Services/IStatisticsControllerService.cs
> +public interface IStatisticsControllerService
Заменил на IStatisticsService

2022-10-24 08:54 UTC, SergerGood commented on BL/Services/StatisticsControllerService.cs
> +public class StatisticsControllerService
перешлю в телеге

2022-10-24 13:02 UTC, closed without merging