Unit of work
prplmad/Monitoring pull request #10
Opened 2022-11-17 13:39 UTC by prplmad

2022-11-21 05:37 UTC, alexander-eltsov requested changes

2022-11-21 05:37 UTC, alexander-eltsov commented on Persistence/UoW/UnitOfWork.cs
> +            Dispose();
Лучше не вызывать Dispose при комите транзакции. Поведение может быть не очевидным.

2022-11-21 05:37 UTC, alexander-eltsov commented on Persistence/Repositories/EventRepository.cs
> +        await connection.ExecuteAsync(new CommandDefinition(query, eventForCreation, cancellationToken: cancellationToken, transaction:await _connectionFactory.CreateTransactionAsync()));
Репозиторий не должен инициировать создание транзакции. Представь, что тебе потребуется в рамках одной транзакции вызвать несколько методов в различных репозиториях. Изменения должны быть атомарны, поэтому лучше создавать транзакцию выше и "прокидывать" ее до репозитория

2022-11-21 05:43 UTC, alexander-eltsov commented on Services/StatisticService.cs
> +        await _unitOfWork.CommitAsync();
Судя по коду этот комит применится только для последней транзакции, т.е. если перед строкой 42 добавить, например, запись в репозиторий EventRepository, то эти данные не применятся, т.к. StatisticRepository пересоздаст новую транзакцию

2022-11-21 09:38 UTC, prplmad commented on Persistence/UoW/UnitOfWork.cs
> +            Dispose();
Убрал Dispose

2022-11-21 09:38 UTC, prplmad commented on Persistence/Repositories/EventRepository.cs
> +        await connection.ExecuteAsync(new CommandDefinition(query, eventForCreation, cancellationToken: cancellationToken, transaction:await _connectionFactory.CreateTransactionAsync()));
Поправил

2022-11-21 09:39 UTC, prplmad commented on Services/StatisticService.cs
> +        await _unitOfWork.CommitAsync();
Проблему понял, поправил

2022-11-23 06:29 UTC, SergerGood requested changes

2022-11-23 06:29 UTC, SergerGood commented on Persistence/Repositories/StatisticRepository.cs
> +        using (_connection)
когда мы вынесли управление connection-ом, то не стоит оборачивать его в using. Так мы сломаем поведение и ответственность UOW

2022-11-23 06:29 UTC, SergerGood commented on Persistence/Repositories/StatisticRepository.cs
> +            var statistics = await _connection.QueryAsync<Statistic>(new CommandDefinition(query, cancellationToken: cancellationToken));
если у нас есть транзакция, то лучше ее передавать во все методы

2022-11-23 06:29 UTC, SergerGood commented on Persistence/UoW/UnitOfWork.cs
> +        if (_connection.State != ConnectionState.Open)
кажется перемудрил. connection создается здесь, и вряд ли он будет открыт пока мы его не откроем. Да и если он уже открыт, то по этому условию не факт что будет создана транзакция

2022-11-23 06:29 UTC, SergerGood commented on Persistence/UoW/UnitOfWork.cs
> +            _transaction.Rollback();
Rollback делать, когда не удался Commit смысла нет, потому что просто данные не закомичены. А вот делать  Rollback на Dispose логичнее, потому что если не вызвали Commit, то надо все отролбэчить

2022-11-23 06:29 UTC, SergerGood commented on Persistence/UoW/UnitOfWork.cs
> +            _transaction.Commit();
еще не плохо бы закрывать соединении после коммита, чтобы его никто больше не использовал, по крайней мере не осознано

2022-11-23 06:29 UTC, SergerGood commented on WebApp/Program.cs
> +public partial class Program
похоже на что-то лишнее

2022-11-23 06:29 UTC, SergerGood commented on Persistence/UoW/UnitOfWork.cs
> +        if (!disposed)
а можешь рассказать зачем здесь это?

2022-11-23 06:29 UTC, SergerGood commented on Persistence/Connection/ConnectionFactory.cs
> +    private IDbConnection _dbConnection;
не понял зачем выделять локальную перемнную

2022-11-23 11:29 UTC, prplmad commented on Persistence/Repositories/StatisticRepository.cs
> +        using (_connection)
Убрал using

2022-11-23 11:29 UTC, prplmad commented on Persistence/Repositories/StatisticRepository.cs
> +            var statistics = await _connection.QueryAsync<Statistic>(new CommandDefinition(query, cancellationToken: cancellationToken));
поправил

2022-11-23 11:29 UTC, prplmad commented on Persistence/UoW/UnitOfWork.cs
> +        if (_connection.State != ConnectionState.Open)
Убрал условие

2022-11-23 11:31 UTC, prplmad commented on Persistence/UoW/UnitOfWork.cs
> +            _transaction.Rollback();
Добавил Rollback в метод Dispose. Для того, чтобы не возникало ошибки из-за закрытия соединения после комита, добавил условие if (_connection.State == ConnectionState.Open)

2022-11-23 11:31 UTC, prplmad commented on Persistence/UoW/UnitOfWork.cs
> +            _transaction.Commit();
поправил

2022-11-23 11:31 UTC, prplmad commented on WebApp/Program.cs
> +public partial class Program
убрал

2022-11-23 11:32 UTC, prplmad commented on Persistence/UoW/UnitOfWork.cs
> +        if (!disposed)
убрал это условие

2022-11-23 11:32 UTC, prplmad commented on Persistence/Connection/ConnectionFactory.cs
> +    private IDbConnection _dbConnection;
поправил

2022-11-25 06:08 UTC, SergerGood requested changes

2022-11-25 06:08 UTC, SergerGood commented on Persistence/Repositories/StatisticInMemoryRepository.cs
> +        await Task.Delay(0);
правильнее будет await Task.FromResult(), когда возвращаем результат
а здесь await Task.CompletedTask

2022-11-25 07:29 UTC, prplmad commented on Persistence/Repositories/StatisticInMemoryRepository.cs
> +        await Task.Delay(0);
поправил

2022-11-25 07:37 UTC, SergerGood commented on Persistence/Repositories/StatisticInMemoryRepository.cs
> +        await Task.Delay(0);
await Task.CompletedTask; делаю в конце метода
а для метода GetAllAsync на сделать вот так return await Task.FromResult(sortedStatistics);

2022-11-25 07:38 UTC, prplmad commented on Persistence/Repositories/StatisticInMemoryRepository.cs
> +        await Task.Delay(0);
Метод GetAllAsync  уже поправил в последнем коммите, поспешил с ним.

await Task.CompletedTask сейчас поправлю

2022-11-25 07:39 UTC, prplmad commented on Persistence/Repositories/StatisticInMemoryRepository.cs
> +        await Task.Delay(0);
поправил

2022-11-25 07:42 UTC, SergerGood approved these changes

2022-11-25 07:44 UTC, merged