SignalR
prplmad/Monitoring pull request #11
Opened 2022-11-24 13:01 UTC by prplmad

2022-11-24 16:44 UTC, prplmad commented on WebApp/client/src/app/statistics-list/statistics-list.component.ts
> +    this.connection.on("notifycreatestatistic", () => this.getStatistics);
разобрался почему не работало, надо так
this.connection.on("notifycreatestatistic", () => this.getStatistics**()**);

2022-11-28 06:03 UTC, alexander-eltsov requested changes

2022-11-28 06:03 UTC, alexander-eltsov commented on Services/EventService.cs
> +        using (_unitOfWork)
`using (_unitOfWork)`

Так лучше не делать. Есть риск в вызывающем коде отхватить ObjectDisposedException. Обычно тот кто создает экземпляр Disposable объекта, тот и должен вызвать Dispose (через using).
Конкретно в твоем случае получается, что вызывающий код передает свой экземпляр unit of work при вызове GetEventsByStatisticIdAsync, который в итоге "уничтожает" его.

2022-11-28 06:03 UTC, alexander-eltsov commented on WebApp/client/package.json
> +    "@microsoft/signalr": "^7.0.0",
Лучше использовать версию @microsoft/signalr, соотносящуюся с версией dotnet на бекенде. В твоем проекте используется .NET6, поэтому и signalr клиент лучше тоже взять версии 6.X

2022-11-28 06:03 UTC, alexander-eltsov commented on WebApp/client/src/app/statistics-list/statistics-list.component.ts
> +    this.destroyed$.unsubscribe();
complete все равно должен быть, иначе могут остаться другие живые подписки, которые ожидают завершения последовательности this.destroyed

2022-11-28 06:03 UTC, alexander-eltsov commented on Persistence/Repositories/StatisticInMemoryRepository.cs
> +        return await Task.FromResult(0);
Почему возвращает 0? Из контракта IStatisticRepository не читается, что вызывающий код может ожидать от возвращаемого значения. Идентификатор статистики? Количество добавленных записей? Или что-то еще?
Формально это нарушение принципа Liskov из SOLID'а про согласованность производного типа относительно контракта. В твоем коде присутствуют 2 реализации контракта IStatisticRepository и они по разному трактуют возвращаемое значение для метода CreateAsync, что говорит либо о неточности контракта, либо о некорректности реализации.

2022-11-28 08:33 UTC, prplmad commented on Services/EventService.cs
> +        using (_unitOfWork)
Если я правильно понял, то using не нужен, поскольку метод Dispose все равно будет вызываться вместе с завершением запроса (т.к. жизненный цикс сервиса UoW - Scoped). Убрал using

2022-11-28 08:33 UTC, prplmad commented on WebApp/client/package.json
> +    "@microsoft/signalr": "^7.0.0",
Поправил

2022-11-28 08:34 UTC, prplmad commented on WebApp/client/src/app/statistics-list/statistics-list.component.ts
> +    this.destroyed$.unsubscribe();
Вернул обратно

2022-11-28 08:35 UTC, prplmad commented on Persistence/Repositories/StatisticInMemoryRepository.cs
> +        return await Task.FromResult(0);
Это было временное решение) сделал, чтобы возвращал id статистики

2022-11-28 10:26 UTC, alexander-eltsov commented on Services/EventService.cs
> +        using (_unitOfWork)
Верно

2022-11-28 10:29 UTC, alexander-eltsov commented on Persistence/Repositories/StatisticInMemoryRepository.cs
> +        return await Task.FromResult(0);
Проблема в контракте все еще сохраняется. По сигнатуре метода и sml комментариям не ясно, что нужно возвращать при реализации контракта. Имеет смысл указать про id статистики в комментарии.
<returns>Возвращается Task.</returns>

2022-11-28 11:08 UTC, prplmad commented on Persistence/Repositories/StatisticInMemoryRepository.cs
> +        return await Task.FromResult(0);
Вроде бы этот момент я тоже учел, я что-то упускаю? 
![image](https://user-images.githubusercontent.com/44546513/204262952-18bc5529-5a04-4ba6-8e65-12cb657896a7.png)

2022-11-30 10:12 UTC, alexander-eltsov commented on Persistence/Repositories/StatisticInMemoryRepository.cs
> +        return await Task.FromResult(0);
Не заметил сразу, так гораздо лучше 👍

2022-11-30 10:12 UTC, alexander-eltsov approved these changes

2022-11-30 13:33 UTC, merged