Spa integration
prplmad/Monitoring pull request #4
Opened 2022-10-28 12:32 UTC by prplmad

2022-10-28 14:30 UTC, alexander-eltsov requested changes
Нестыковка получается. Раз мы решили делать spa + web api на одном хосте, то кажется, что имя WebApi для корневой директории только усложнит восприятие кода. Не очевидно, что в недрах спрятам web app клиент

2022-10-28 14:30 UTC, alexander-eltsov commented on WebApi/client/src/app/statistic.ts
> +export class Statistic {
BTW. В typescript используется "утиная" типизация (duck-typing). Часто удобнее для структурных данных / моделей использовать interface'ы вместо class'ов, т.к. в typescript любой object можно привести к ссылке по интерфейсу и компилятор сам проверит все ли поля и методы контракты интерфеса присутствуют в объекте.
Само использование класса тут вовсе не ошибка

2022-10-28 14:30 UTC, alexander-eltsov commented on WebApi/client/src/app/data.service.ts
> +  getStatistics() {
Хорошим тоном будет сразу выработать привычку всегда указывать возвращаемый тип. Это позволит уменьшить проблемы при не преднамеренной "подмене" возвращаемого типа

2022-10-28 14:30 UTC, alexander-eltsov commented on WebApi/client/src/app/app.component.ts
> +      .subscribe((data: any) => this.statistics = data as Statistic[]);
Идеология RxJS такова, что лучше по максимумму возвращать Observable и не делать скрытых подписок в методах. Т.е. этот метод возвращает нужный Observable (указываем также тип данных), а потребитель метода создает подписку на Observable.
Получается метод loadStatistics должен вернуть Observable, а его вызов в ngOnInit() должен создать подписку. Таким образом не плодятся лишние подписки-фантомы, не течет память и вызывающий код может органично встроиться в pipe и добавить свои преобразования.
И на развитие сразу предупрежу, что важно вести учет этих самых подписок (объекты в результате вызова subscribe() над observable). Тут на помощь приходит angular lifecycle hook OnDestroy (https://angular.io/api/core/OnDestroy) и rx метод unsubscribe() на подписке или rx оператор takeUntill()
Например, вот так https://stackoverflow.com/questions/42490265/rxjs-takeuntil-angular-components-ngondestroy

2022-10-28 14:30 UTC, alexander-eltsov commented on WebApi/client/src/app/app.component.spec.ts
> +import { TestBed } from '@angular/core/testing';
spec файлы можно не создавать, тесты для ui писать не придется
Если для генерации файлов используешь ng cli, т.е возможность заставить его не добавлять постоянно spec файлы
https://stackoverflow.com/questions/42049756/angular-9-cli-typescript-how-to-stop-generating-spec-ts-test-files

2022-10-31 12:25 UTC, prplmad commented on WebApi/client/src/app/statistic.ts
> +export class Statistic {
Поменял на interface

2022-10-31 12:25 UTC, prplmad commented on WebApi/client/src/app/data.service.ts
> +  getStatistics() {
Исправил

2022-10-31 12:26 UTC, prplmad commented on WebApi/client/src/app/app.component.ts
> +      .subscribe((data: any) => this.statistics = data as Statistic[]);
сделал

2022-10-31 12:26 UTC, prplmad commented on WebApi/client/src/app/app.component.spec.ts
> +import { TestBed } from '@angular/core/testing';
Понял, спасибо! Удалил.

2022-10-31 12:42 UTC, alexander-eltsov commented on WebApi/client/src/app/app.component.ts
> +      .subscribe((data: any) => this.statistics = data as Statistic[]);
Не доделал. Метод ngOnDestroy() в компоненте StatisticsListComponent присутствует, но интерфейс OnDestroy не наследуется. Angular не в курсе, что этот компонент содержит доп логику при его уничтожении.

2022-10-31 12:56 UTC, prplmad commented on WebApi/client/src/app/app.component.ts
> +      .subscribe((data: any) => this.statistics = data as Statistic[]);
исправил

2022-11-01 09:24 UTC, merged