Подключил NSwag, тесты, подключил Seq
prplmad/Monitoring pull request #5
Opened 2022-11-01 11:15 UTC by prplmad

2022-11-01 13:29 UTC, SergerGood requested changes

2022-11-01 13:29 UTC, SergerGood commented on Tests/Tests.csproj
> +        <CodeAnalysisRuleSet>C:\Analyzer\infotecs.ruleset</CodeAnalysisRuleSet>
относительный путь ;)

2022-11-01 13:29 UTC, SergerGood commented on WebApp/Program.cs
> +builder.Services.AddSwaggerDocument();
пробегись плиз https://learn.microsoft.com/ru-ru/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-6.0&tabs=visual-studio
идеально если после этого контроллер чуть больше опишешь

2022-11-01 13:29 UTC, SergerGood commented on Tests/StatisticServiceTests.cs
> +using NUnit.Framework;
пока не убежали давай на xunit все-таки сделаем, просто если до этого не работал с ним, то лучше попробовать

2022-11-01 13:29 UTC, SergerGood commented on Tests/StatisticServiceTests.cs
> +        Assert.Throws<StatisticNotFoundException>(() => { throw new StatisticNotFoundException(It.IsAny<int>()); });
это не так работает,  должно быть: Assert.Throws<StatisticNotFoundException>(() => _statisticService.UpdateAsync(It.IsAny<StatisticForUpdatingDto>(), It.IsAny<CancellationToken>()));

т.е. ловится ошибка вызова метода, а не ошибка вызова ошибки

2022-11-02 07:18 UTC, alexander-eltsov commented on Tests/StatisticServiceTests.cs
> +        Assert.Throws<StatisticNotFoundException>(() => { throw new StatisticNotFoundException(It.IsAny<int>()); });
+1
Вообще стоит начинать писать тест с говорящего имени. Один из распространенных паттернов наименования это [MethodName]_[Scenario]_[ExpectedResult]
, где
- MethodName - имя тестируемого метода
- Scenario - тестируемое состояние, сценарий или входные данные
- ExpectedResult - ожидаемое поведение или значение

Секции паттерна соответствуют Arrange, Act и Assert

В твоем случае UpdateAsync_StatisticRepositoryThrowsException не ясно StatisticRepositoryThrowsException это условие выполенения теста или же ожидание/проверяемое состояние
Предложу такой вариант:
UpdateAsync_RecordNotFoundInRepository_ThrowsStatisticNotFoundException
Что можно расшифровать как "Тестируем метод UpdateAsync при условии, что запись отсутствует в репозитории, ожидается, что метод сгенерирует исключение StatisticNotFoundException"

2022-11-02 07:18 UTC, alexander-eltsov commented on WebApp/appsettings.json
> -        "Name": "File",
На практике часто бывает по несколько sink'ов сконфигурировано для serilog. В проде может и не быть Seq, тогда хоть вывод логов в файл останется

2022-11-02 07:18 UTC, alexander-eltsov commented on Tests/StatisticServiceTests.cs
> +        Assert.Throws<StatisticNotFoundException>(() => { throw new StatisticNotFoundException(It.IsAny<int>()); });
+1
Вообще стоит начинать писать тест с говорящего имени. Один из распространенных паттернов наименования это [MethodName][Scenario][ExpectedResult]
, где

MethodName - имя тестируемого метода
Scenario - тестируемое состояние, сценарий или входные данные
ExpectedResult - ожидаемое поведение или значение
Секции паттерна соответствуют Arrange, Act и Assert

В твоем случае UpdateAsync_StatisticRepositoryThrowsException не ясно StatisticRepositoryThrowsException это условие выполенения теста или же ожидание/проверяемое состояние
Предложу такой вариант:
UpdateAsync_RecordNotFoundInRepository_ThrowsStatisticNotFoundException
Что можно расшифровать как "Тестируем метод UpdateAsync при условии, что запись отсутствует в репозитории, ожидается, что метод сгенерирует исключение StatisticNotFoundException"

2022-11-02 09:11 UTC, prplmad commented on Tests/Tests.csproj
> +        <CodeAnalysisRuleSet>C:\Analyzer\infotecs.ruleset</CodeAnalysisRuleSet>
поправил

2022-11-02 09:12 UTC, prplmad commented on WebApp/Program.cs
> +builder.Services.AddSwaggerDocument();
Постарался описать подробнее, как в статье

2022-11-02 09:13 UTC, prplmad commented on Tests/StatisticServiceTests.cs
> +using NUnit.Framework;
Поменял nUnit на xUnit

2022-11-02 09:13 UTC, prplmad commented on Tests/StatisticServiceTests.cs
> +        Assert.Throws<StatisticNotFoundException>(() => { throw new StatisticNotFoundException(It.IsAny<int>()); });
Ошибку понял, поправил

2022-11-02 09:13 UTC, prplmad commented on WebApp/appsettings.json
> -        "Name": "File",
Вернул вывод логов в файл

2022-11-02 13:51 UTC, alexander-eltsov commented on Tests/StatisticServiceTests.cs
> +        Assert.Throws<StatisticNotFoundException>(() => { throw new StatisticNotFoundException(It.IsAny<int>()); });
Еще нужно скорректировать. Сейчас метод UpdateAsync дважды вызывается, один раз в разделе Act, а второй внутри Assert.ThrowsAsync и оба раза тест результата не ожидает.
Сейчас у тебя тест проходит из-за некорректного использования модели асинхронного программирования.
Этот тест должен возвращать Task (xUnit поддерживает Task'и), а завершение вызова UpdateAsync нужно дожидаться с помощью await.

2022-11-03 08:53 UTC, prplmad commented on Tests/StatisticServiceTests.cs
> +        Assert.Throws<StatisticNotFoundException>(() => { throw new StatisticNotFoundException(It.IsAny<int>()); });
скорректировал

2022-11-03 10:29 UTC, alexander-eltsov commented on Tests/StatisticServiceTests.cs
> +        Assert.Throws<StatisticNotFoundException>(() => { throw new StatisticNotFoundException(It.IsAny<int>()); });
вот теперь то, что надо

2022-11-03 10:30 UTC, alexander-eltsov approved these changes

2022-11-03 10:48 UTC, merged