Db
prplmad/Monitoring pull request #6
Opened 2022-11-03 13:29 UTC by prplmad

2022-11-07 06:31 UTC, SergerGood requested changes

2022-11-07 06:31 UTC, SergerGood commented on Persistence/Context/DapperContext.cs
> +    public IDbConnection CreateConnection() => new SqlConnection(_connectionString);
кажется мы говорили про PostgreSql?)

2022-11-07 06:31 UTC, SergerGood commented on Persistence/Context/DapperContext.cs
> +public class DapperContext
Мне кажется здесь больше подойдет классическое название с *ConnectionFactory*, контекста тут явно нет

2022-11-07 06:31 UTC, SergerGood commented on Persistence/Repositories/StatisticRepository.cs
> +    public async Task<IReadOnlyCollection<Statistic>> GetAllAsync(CancellationToken cancellationToken = default)
cancellationToken пока выглядит бесполезным, или тогда уж используем CommandDefinition

2022-11-07 06:31 UTC, SergerGood commented on WebApp/appsettings.json
> +    "MyDb" : "Server=localhost\\postgres;Database=postgres;Integrated Security=true;"
давай лучше через юзер/пароль, не уверен, что такое легко взлетит на Linux

2022-11-07 07:44 UTC, prplmad commented on Persistence/Context/DapperContext.cs
> +    public IDbConnection CreateConnection() => new SqlConnection(_connectionString);
+ увидел потом, что не тот Connection использую

2022-11-07 11:05 UTC, prplmad commented on Persistence/Context/DapperContext.cs
> +    public IDbConnection CreateConnection() => new SqlConnection(_connectionString);
поправил

2022-11-07 11:05 UTC, prplmad commented on Persistence/Context/DapperContext.cs
> +public class DapperContext
поправил

2022-11-07 11:07 UTC, prplmad commented on Persistence/Repositories/StatisticRepository.cs
> +    public async Task<IReadOnlyCollection<Statistic>> GetAllAsync(CancellationToken cancellationToken = default)
использовал CommandDefinition, вроде бы работает - при отмене запроса в постмане ловится Exception, проверял на длительном запросе, используя функцию pg_sleep(10): 
select * from statistic s, pg_sleep(10)

2022-11-07 11:08 UTC, prplmad commented on WebApp/appsettings.json
> +    "MyDb" : "Server=localhost\\postgres;Database=postgres;Integrated Security=true;"
поправил

2022-11-07 13:06 UTC, SergerGood requested changes

2022-11-07 13:06 UTC, SergerGood commented on Persistence/Migrations/AddStatisticTable_20221106.cs
> +                .WithColumn("os").AsString().NotNullable()
у нас по описанию точно все поля обязательные?

2022-11-07 13:06 UTC, SergerGood commented on Persistence/Migrations/Database.cs
> +        var query = "SELECT datname FROM pg_database where \"datname\" = @name";
Давай вот это попробуем DefaultTypeMap.MatchNamesWithUnderscores = true;

2022-11-07 13:06 UTC, SergerGood commented on Persistence/Migrations/Database.cs
> +        var parameters = new DynamicParameters();
DynamicParameters тяжеловато, вполне себе не плохо работают анонимные типы с даппером

2022-11-07 13:06 UTC, SergerGood commented on Persistence/Persistence.csproj
> +    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.0.1" />
Microsoft.Data.SqlClient уже лишнее

2022-11-07 13:06 UTC, SergerGood commented on WebApp/appsettings.json
> +    "MyDb" : "Server=localhost;Database=postgres;Integrated Security=true; User ID=postgres; Password=er42k2l5"
Integrated Security=true; уже лишнее

2022-11-07 13:06 UTC, SergerGood commented on Persistence/Migrations/Database.cs
> +public class Database
может лучше что-то типа DatabaseCreator

2022-11-07 13:06 UTC, SergerGood commented on Persistence/Repositories/StatisticRepository.cs
> +        var parameters = new DynamicParameters();
и здесь о чем писал в классе Database

2022-11-07 13:06 UTC, SergerGood commented on WebApp/Extensions/MigrationManager.cs
> +                databaseService.CreateDatabase("postgres");
"postgres" лучше брать из конфигурации

2022-11-07 13:06 UTC, SergerGood commented on WebApp/Extensions/MigrationManager.cs
> +            catch
не понятно зачем здесь пусто catch

2022-11-07 13:07 UTC, SergerGood commented on Persistence/Context/DapperContext.cs
> +public class DapperContext
Можно было добавить от себя что-то, ну ладно)

2022-11-07 13:48 UTC, alexander-eltsov requested changes

2022-11-07 13:48 UTC, alexander-eltsov commented on Persistence/Repositories/StatisticRepository.cs
> +    public StatisticRepository(ConnectionFactory connectionFactory)
Зависимость от ConnectionFactory автоматом делает StatisticRepository зависимым и от неймспейса Npgsql. Реализация StatisticRepository зависит от универсальной ORM Dapper, а использование жесткой зависимости в виде ConnectionFactory фактически блокирует нас на Npgsql.
Если потребуется, например, написать модульный тест для данного репозитория, то возникнут проблемы с инъекцией ConnectionFactory. Придется имитировать или держать реальное подключение к PostgreSQL.
Зависимость от абстракций всегда предпочтительнее зависимости от реализации. Лучше выделить интерфейс IConnectionFactory и использовать его

2022-11-07 13:48 UTC, alexander-eltsov commented on WebApp/Program.cs
> +        .ScanIn(Assembly.Load("Persistence")));
Переименование Persistence сборки, например, в DAL, может поломать миграции. Что хуже, разработчик может этого и не заметить, ведь у него на машине миграция уже применена. Лучше использовать типизированные API, например, так
typeof(AddStatisticTable_20221107).Assembly

2022-11-08 07:54 UTC, prplmad commented on Persistence/Migrations/AddStatisticTable_20221106.cs
> +                .WithColumn("os").AsString().NotNullable()
В задании об этом ничего не сказано

2022-11-08 10:35 UTC, SergerGood commented on Persistence/Migrations/AddStatisticTable_20221106.cs
> +                .WithColumn("os").AsString().NotNullable()
https://github.com/prplmad/Monitoring/blob/9dbf61b311ab90f6825ce2bfee5f6f77aefe2402/Domain/Entities/Statistic.cs#L16

у тебя по модели они вроде не обязательные

2022-11-08 13:00 UTC, prplmad commented on Persistence/Migrations/AddStatisticTable_20221106.cs
> +                .WithColumn("os").AsString().NotNullable()
Поправил - добавил миграцию, в которой убрал NotNullable у столбцов

2022-11-08 13:00 UTC, prplmad commented on Persistence/Migrations/Database.cs
> +        var query = "SELECT datname FROM pg_database where \"datname\" = @name";
Сделал

2022-11-08 13:01 UTC, prplmad commented on Persistence/Migrations/Database.cs
> +        var parameters = new DynamicParameters();
Заменил на анонимные типы

2022-11-08 13:01 UTC, prplmad commented on Persistence/Persistence.csproj
> +    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.0.1" />
Убрал

2022-11-08 13:01 UTC, prplmad commented on WebApp/appsettings.json
> +    "MyDb" : "Server=localhost;Database=postgres;Integrated Security=true; User ID=postgres; Password=er42k2l5"
Убрал

2022-11-08 13:01 UTC, prplmad commented on Persistence/Migrations/Database.cs
> +public class Database
Переименовал

2022-11-08 13:01 UTC, prplmad commented on Persistence/Repositories/StatisticRepository.cs
> +        var parameters = new DynamicParameters();
Поправил

2022-11-08 13:01 UTC, prplmad commented on WebApp/Extensions/MigrationManager.cs
> +                databaseService.CreateDatabase("postgres");
Поправил

2022-11-08 13:02 UTC, prplmad commented on WebApp/Extensions/MigrationManager.cs
> +            catch
Убрал блок try catch

2022-11-08 13:02 UTC, prplmad commented on Persistence/Repositories/StatisticRepository.cs
> +    public StatisticRepository(ConnectionFactory connectionFactory)
Поправил

2022-11-08 13:02 UTC, prplmad commented on WebApp/Program.cs
> +        .ScanIn(Assembly.Load("Persistence")));
Поправил

2022-11-09 08:23 UTC, SergerGood commented on Persistence/Migrations/Database.cs
> +        var query = "SELECT datname FROM pg_database where \"datname\" = @name";
Это вещь статика поэтому можно проинициализировать один раз. Где-то в начале запуска хоста

2022-11-09 08:26 UTC, SergerGood commented on Persistence/Migrations/Database.cs
> +        var parameters = new DynamicParameters();
я немного тебя запутал) смотри, там на самом деле можно сам объект передать, а анонимные, это когда работаем не с самой моделью. Т.е.:
`await connection.ExecuteAsync(new CommandDefinition(query, **statistic**, cancellationToken: cancellationToken));`

2022-11-09 08:29 UTC, SergerGood commented on Persistence/Migrations/Database.cs
> +public class Database
тогда может и название метод упростим, а то по сути у тебя получается CreateDatabase.CreateDatabase. Ты конечно Creator заинжектил с другим именем (databaseService), но тут я бы тебе посоветовал все-таки инжектить с тем же именем.

2022-11-09 10:13 UTC, prplmad commented on Persistence/Migrations/Database.cs
> +        var parameters = new DynamicParameters();
Поправил

2022-11-09 10:14 UTC, prplmad commented on Persistence/Migrations/Database.cs
> +        var query = "SELECT datname FROM pg_database where \"datname\" = @name";
Добавил в конструктор ConnectionFactory

2022-11-09 10:14 UTC, prplmad commented on Persistence/Migrations/Database.cs
> +public class Database
Переименовал

2022-11-09 10:26 UTC, SergerGood commented on Persistence/Migrations/Database.cs
> +        var query = "SELECT datname FROM pg_database where \"datname\" = @name";
Смотри. Хоть ConnectionFactory у нас и синглтон, но это не совсем его ответственность. Он как минимум не знает ничего о дапере + кто-то может воспользоваться даппером не проинициализировав фабрику. Это все-таки конфигурация и поэтому я намекал, что лучше делать при инициализации хоста. У нас в Program уже накопилась логика по работе с данными. Если ее выделить в метод и добавить туда эту статику, тогда все будет в одном месте.

2022-11-09 10:27 UTC, SergerGood commented on Persistence/Migrations/Database.cs
> +        var parameters = new DynamicParameters();
А всех-таки нельзя разве сразу  statistic передавать вместо statisticQuery?

2022-11-09 11:16 UTC, prplmad commented on Persistence/Migrations/Database.cs
> +        var parameters = new DynamicParameters();
Можно, я до конца думал, что надо использовать все-таки анонимный тип) поправил

2022-11-09 11:17 UTC, prplmad commented on Persistence/Migrations/Database.cs
> +        var query = "SELECT datname FROM pg_database where \"datname\" = @name";
Выделил в отдельный метод

2022-11-09 11:41 UTC, SergerGood commented on Persistence/Extensions/DependencyInjection/DependencyInjectionExtencions.cs
> +    /// <param name="services">IServiceCollection.</param>
Есть кстати такая вещь как https://learn.microsoft.com/ru-ru/dotnet/csharp/language-reference/xmldoc/recommended-tags#see

2022-11-09 11:43 UTC, SergerGood approved these changes

2022-11-09 11:58 UTC, merged