Добавил таблицу Event
prplmad/Monitoring pull request #8
Opened 2022-11-09 13:35 UTC by prplmad

2022-11-09 16:25 UTC, alexander-eltsov requested changes

2022-11-09 16:25 UTC, alexander-eltsov commented on Persistence/Migrations/AddEventsTable_20221109.cs
> +            .WithColumn("name").AsString(50).Nullable()
Кажется, что имя события также можно отнести к требуемым данным. Иначе несколько странно получается, приложение присылает инфу, что произошло что-то тогда-то, а что именно не понятно.

2022-11-10 13:10 UTC, prplmad commented on Persistence/Migrations/AddEventsTable_20221109.cs
> +            .WithColumn("name").AsString(50).Nullable()
Поправил

2022-11-11 14:02 UTC, alexander-eltsov requested changes

2022-11-11 14:02 UTC, alexander-eltsov commented on Contracts/StatisticWithEventsDto.cs
> +    public IEnumerable<EventDto>? Events { get; set; }
Для множеств dto удобнее сразу инициализировать массивы/коллекции. Тогда не придется null ref предупреждения везде учитывать. Например, так:
public EventDto[] Events { get; set; } = Array.Empty<EventDto>()

2022-11-11 14:02 UTC, alexander-eltsov commented on Persistence/Repositories/EventRepository.cs
> +    public async Task<Statistic> GetEventsByStatisticIdAsync(int statisticId, CancellationToken cancellationToken = default)
Раз мы выделяем две разные сущности, то проще будет не использовать агрегацию событий в модели статистики (Statistic.Events), т.е. если нужно получить events, то используешь этот репозитория и по statisticId получаешь список events.
Тогда уйдут и странности для потребителей этих репозиториев. IEventRepository предназначен для работы с экземплярами Event, а StatisticRepository для работы с статистикой. Хотя для последнего нейминг получается не совсем удачный - это скорее устройство, для которого прилетают события.

Альтернативный вариант будет иметь один aggregate root - Statistic (как сейчас на уровне моделей), но тогда и репозиторий должен быть один. Данные через dapper можно вытянуть за раз, например, используя splitOn для соединенных (join) данных https://www.learndapper.com/relationships

2022-11-11 14:02 UTC, alexander-eltsov commented on Services/EventService.cs
> +            var statisticWithEventsDtos = statisticWithEvents.Adapt<StatisticWithEventsDto>();
Это преобразование более корректно держать вне сервиса. Сервисы это часть Business Logic, работают на доменных моделях, а dto - это POCO транспортные объекты, т.е. они могут быть специфичны для транспорта! Иначе, если возникнет необходимость пересесть с JSON на gRPC, то изменения коснутся не только контроллеров, но и Business Logic слоя
dto -> controller -> Adapt<Model> -> ModelService.Invoke() -> Adapt<Result> to dto

2022-11-11 14:02 UTC, alexander-eltsov commented on Services/EventService.cs
> +            throw new StatisticNotFoundException(eventForCreationDto.StatisticId);
Если код нарушит, например, ограничение длины имени события, тогда оператор INSERT внутри сгенерирует ошибку и получится, что данный cacth блок перехватит ее и подменит ошибку на "Статистика не найдена"

2022-11-11 14:02 UTC, alexander-eltsov commented on Domain/Entities/Event.cs
> +    public string? Name { get; set; }
Согласно текущей миграции, БД не позволяет хранить NULL значения для событий. Тогда и в модели использовать null ref type ник чему.

2022-11-14 13:10 UTC, prplmad commented on Contracts/StatisticWithEventsDto.cs
> +    public IEnumerable<EventDto>? Events { get; set; }
т.к. решил оставить два репозитория, то убрал коллекцию событий у сущности Statistic, совет на будущее учел

2022-11-14 13:12 UTC, prplmad commented on Persistence/Repositories/EventRepository.cs
> +    public async Task<Statistic> GetEventsByStatisticIdAsync(int statisticId, CancellationToken cancellationToken = default)
Решил пока оставить две сущности, почитал про Agregation Root в ddd, но с ходу пока понять как это правильно реализуется не получилось.

2022-11-14 13:13 UTC, prplmad commented on Services/EventService.cs
> +            var statisticWithEventsDtos = statisticWithEvents.Adapt<StatisticWithEventsDto>();
Перенес маппинг в контроллеры

2022-11-14 13:15 UTC, prplmad commented on Services/EventService.cs
> +            throw new StatisticNotFoundException(eventForCreationDto.StatisticId);
Пока что убрал try catch, буду завтра думать, как сделать лучше

2022-11-14 13:15 UTC, prplmad commented on Domain/Entities/Event.cs
> +    public string? Name { get; set; }
Поправил

2022-11-14 18:26 UTC, alexander-eltsov commented on Domain/Entities/Event.cs
> +    [StringLength(50)]
Кто валидирует этот атрибут? Насколько я вижу, такого кода нет. Когда мы используем атрибуты из неймспейса DataAnnotations в dto, то ASP.NET сам валидирует их при биндинге на типы метода контроллера. А если мы собираемся использовать атрибуты и в моделях BL слоя, то потребуется дополнительно и некий валидатор. Можно же создать экземпляр Event модели в памяти с именем больше 50 символов?
Обычно валидаторы моделей (не dto'шек) оформляют в виде отдельных сервисов, классов-правил, расширений и пр. Посмотри как делают валидацию моделей с помощью популярной библиотеки FluentValidation https://docs.fluentvalidation.net/en/latest/ У нас она тоже используется

2022-11-14 18:30 UTC, alexander-eltsov commented on Services/EventService.cs
> +            throw new StatisticNotFoundException(eventForCreationDto.StatisticId);
Из сервиса ушел мэппинг, ушели try catch. Текущий сервис получается просто "перекладывает" запросы из контроллера в репозитории. Это вполне нормальная ситуация. Бывают и бекенда, где нет тяжелой бизнес логики и тогда могут существовать всего 2 слоя: presentation и dal.
Если сделаешь валидацию моделей, то ее как раз можно вызывать в этих сервисах и обрабатывать невалидные модели

2022-11-14 18:42 UTC, alexander-eltsov approved these changes

2022-11-15 10:26 UTC, prplmad commented on Domain/Entities/Event.cs
> +    [StringLength(50)]
Валидацию бизнес моделей добавил

2022-11-15 11:14 UTC, merged